# Generated by Django 3.2.7 on 2022-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0003_dataset_tipofonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='serie',
            field=models.BigIntegerField(unique=True, verbose_name='serie'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tipo',
            field=models.CharField(max_length=100, unique=True, verbose_name='tipo'),
        ),
    ]
