# Generated by Django 3.2.7 on 2021-10-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myid', models.IntegerField(verbose_name='myid')),
                ('serie', models.BigIntegerField(verbose_name='serie')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('fonte', models.CharField(max_length=255, verbose_name='fonte')),
            ],
        ),
    ]
